### ISSUE TITLE
HWLSaveEditorGUI

### ISSUE THREAD

**Issue by Maximumride1126** [nedron92/HWL-SaveEditor#2]
Everytime I open it it says "Found a 'zmha.bin' within this dir. Open it?" i click yes and then nothing happens.

**Comment by nedron92** [comment]
If you opened it withou a savefile? 
Version? Stable/Nightly? 
I need more information. I know there was an failure, but I didn't release anything that had this failure.

**Comment by Maximumride1126** [comment]
I've tried it with and without a save file and ive done it on both the stable and the nightly build. Is it possible that there is a failure on my side?

**Comment by nedron92** [comment]
Weired. Normally it should work without any problems, cause I includes all MFC libs into the windows-builds itself.
It can be a failure on your side. Check if you have 
visual c++ redistributable 2012
visual c++ redistributable 2013

one of them installed (or newer). Than it should be work. 
If it doesnt work, I don't know yet where the problem is.

**Comment by nedron92** [comment]
Any News for me @Maximumride1126 ?
